# Generated by Django 6.1 on 2026-08-30 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_sistema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.usuariosistema')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_aplicado', models.CharField(blank=True, max_length=200)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado_envio', models.CharField(choices=[('EXITO', 'Éxito'), ('FALLO', 'Fallo')], max_length=10)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.actividad')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('metodo_ingreso', models.CharField(choices=[('RUT', 'RUT'), ('QR', 'QR'), ('CODIGO', 'Código de barras')], max_length=10)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.alumno')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.usuariosistema')),
            ],
            options={
                'unique_together': {('actividad', 'alumno')},
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='CONFIRMADA', max_length=20)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.alumno')),
            ],
            options={
                'unique_together': {('actividad', 'alumno')},
            },
        ),
    ]
