# Generated by Django 6.1 on 2026-08-30 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_actividad_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='carreras',
            field=models.ManyToManyField(blank=True, to='gestion.carrera'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='jornadas',
            field=models.ManyToManyField(blank=True, to='gestion.jornada'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario_sistema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
