# Generated by Django 6.1 on 2026-08-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_actividad_carreras_alter_actividad_jornadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='actividades/'),
        ),
    ]
