# Generated by Django 6.1 on 2026-08-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_actividad_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='cronograma',
            field=models.TextField(blank=True, null=True, verbose_name='Cronograma de fechas'),
        ),
    ]
