# Generated by Django 6.1 on 2026-09-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_actividad_cronograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
