# Generated by Django 6.1 on 2026-09-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_alumno_rut_alter_usuariosistema_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='escuela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
