# Generated by Django 6.1 on 2026-09-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_carrera_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
