# Generated by Django 6.1 on 2026-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_actividad_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='cambios_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='modulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='objeto_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='objeto_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='objeto_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
