# Generated by Django 6.1 on 2026-09-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_logauditoria_cambios_json_logauditoria_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosistema',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
