# Generated by Django 6.1 on 2026-09-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_usuariosistema_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='rut',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='rut',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
    ]
