# Generated by Django 6.1 on 2026-09-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_alumno_rut_alter_usuariosistema_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ACTIVA', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
