# Generated by Django 6.1 on 2026-09-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_actividad_estado_alter_actividad_fecha_inicio_and_more'),
        ('gestion', '0014_actualizar_escuelas_carreras'),
    ]

    operations = [
    ]
