# Generated by Django 6.1 on 2026-09-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_actualizar_escuelas_carreras_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacioncorreo',
            name='filtro_aplicado',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
