# Generated by Django 6.1 on 2026-09-15 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_notificacioncorreo_filtro_aplicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['escuela', 'nombre'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-fecha_inscripcion'], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='jornada',
            options={'ordering': ['nombre'], 'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Log de auditoría', 'verbose_name_plural': 'Logs de auditoría'},
        ),
        migrations.AlterModelOptions(
            name='notificacioncorreo',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Notificación de correo', 'verbose_name_plural': 'Notificaciones de correo'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['nombre'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuariosistema',
            options={'ordering': ['user__username'], 'verbose_name': 'Usuario del sistema', 'verbose_name_plural': 'Usuarios del sistema'},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='carreras',
            field=models.ManyToManyField(blank=True, related_name='actividades', to='gestion.carrera'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='jornadas',
            field=models.ManyToManyField(blank=True, related_name='actividades', to='gestion.jornada'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion.actividad'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion.alumno'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='metodo_ingreso',
            field=models.CharField(choices=[('RUT', 'RUT'), ('QR', 'Código QR'), ('CODIGO', 'Código de barras')], max_length=10),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='gestion.actividad'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='gestion.alumno'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('LISTA_ESPERA', 'Lista de espera')], default='CONFIRMADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario_sistema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacioncorreo',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestion.actividad'),
        ),
        migrations.AlterField(
            model_name='notificacioncorreo',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestion.alumno'),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='gestion.rol'),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuariosistema', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['-fecha_inicio', 'estado'], name='gestion_act_fecha_i_8b63a9_idx'),
        ),
    ]
