# Generated by Django 6.1 on 2026-09-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_actividad_options_alter_alumno_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tipo_documento',
            field=models.CharField(choices=[('RUT', 'RUT chileno'), ('PASAPORTE', 'Pasaporte extranjero'), ('RUN_PROVISORIO', 'RUN provisorio'), ('CEDULA_EXTRANJERO', 'Cédula de identidad de extranjero')], default='RUT', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='rut',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
