# Generated by Django 6.1 on 2026-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alumno_tipo_documento_alter_alumno_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacioncorreo',
            name='filtro_aplicado',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
