# Generated by Django 6.1 on 2026-09-16 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_alter_notificacioncorreo_filtro_aplicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosistema',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='gestion.rol'),
            preserve_default=False,
        ),
    ]
