# Generated by Django 6.1 on 2026-09-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_alter_asistencia_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='rut',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='RUT/Pasaporte'),
        ),
    ]
